#Database
db:
  dsn: shell:password@(10.2.1.1:3306)/fias2?charset=utf8
  logMode: true
  debug: true
directory:
  filePath: /media/ilarionov/hard-disk/fias/
fiasApi:
  url: https://fias.nalog.ru/WebServices/Public/